version: '3'
services:
  judge:
    environment:
      PYTHONPATH: src/
      NVIDIA_VISIBLE_DEVICES: all  # GPUを有効化
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'judge'
    tty: true
    volumes:
      - .:/build/
    runtime: nvidia  # GPU対応のDockerランタイムを使用